on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 1

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: src/scss/main.scss
          destination: css/main.css

      - name: Compile HTML from PUG files
        run: |
          # Install pug and gomplate
          npm install -g --loglevel=silent pug-cli gomplate

          # Compile top level html files
          if [ -d src/pug ]; then
            find src/pug/*.pug -type f -maxdepth 1 | xargs -I {} pug -b src/pug --out . {}
          fi

          # Compile desserts
          if [ -d src/pug/desserts ]; then
            gomplate -c .=src/pug/desserts/desserts.json --plugin pug=src/scripts/pug_wrapper.sh -t pug_templ=src/pug/desserts/_desserts.pug.templ -f src/pug/templ/gomplate/_desserts.templ
          fi

          # Compile individual pages
          if [ -d src/pug/pages ]; then
            find src/pug/pages -type d -maxdepth 1 -mindepth 1 | xargs -I {} sh -c 'pug -b src/pug --out $(basename {}) {}'
          fi

          # Compile articles
          if [ -d src/pug/articles ]; then
            mkdir -p articles
            gomplate -f src/pug/articles/index.pug.templ | pug -P -b src/pug > articles/index.html
            find src/pug/articles -type d -maxdepth 1 -mindepth 1 | xargs -I {} sh -c 'pug -b src/pug --out articles/$(basename {}) {}'
          fi
      - name: Add and commit changes to main branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add 'css/*.css' '*.html' > /dev/null 2>&1 || true
          if ! git diff --cached --quiet; then
            git commit -m 'Update compiled files'
            git push
          else
            echo "No changes to commit."
          fi
